### ISSUE TITLE
react support?

### ISSUE THREAD

**Issue by eric1lubow** [zzzgydi/webscraper#1]
It cant work  on website which is build by react , such as :https://support.qq.com/products/1368/faqs-more?id=402
I fetch  the page markdown by webscraper ,It show as :
![image](https://github.com/zzzgydi/webscraper/assets/921967/8ccd9748-c170-484d-bbb5-e8bfcf5ca9ee)

I use chrome remote and native, I got the same result

**Comment by zzzgydi** [comment]
This project does support crawling React projects. 

I debugged the test link you provided and found that the page loading takes some time. I couldn't find a very universal way to handle it temporarily, so I won't fix this issue in the source project. However, you can deploy it yourself and add `chromedp.Sleep(1*time.Second),` after line https://github.com/zzzgydi/webscraper/blob/f4c3ecb57945889ae7d3598611735121f8e1a030/service/headless/run.go#L29 of the code.

**Comment by eric1lubow** [comment]
Thank you for your help, my problem has been resolved.
I can think of a way to give the program a parameter to specify the timeout period.
