### ISSUE TITLE
Ubuntu Docker build failed

### ISSUE THREAD

**Issue by HildaM** [zzzgydi/webscraper#2]
# Problems

我在自己的Ubuntu上执行 `sudo docker-compose up` ，出现了以下问题：
```
0.433 go mod download: gopkg.in/yaml.v3@v3.0.1: Get "https://mirrors.aliyun.com/goproxy/gopkg.in/yaml.v3/@v/v3.0.1.info": dial tcp: lookup mirrors.aliyun.com on 100.100.2.138:53: dial udp 100.100.2.138:53: socket: permission denied
------
Dockerfile:13
--------------------
  11 |     # RUN go env -w GOPROXY=https://goproxy.cn,direct
  12 |     RUN go env -w GOPROXY=https://mirrors.aliyun.com/goproxy/,direct
  13 | >>> RUN go mod download
  14 |     COPY . .
  15 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c go mod download" did not complete successfully: exit code: 1
ERROR: Service 'webscraper' failed to build : Build failed
```

我尝试换为阿里源也是出现这种情况。

**Comment by HildaM** [comment]
环境信息：
go version go1.22.2 linux/amd64
Linux

**Comment by zzzgydi** [comment]
这个错误通常是由于 `go mod download` 命令在尝试从指定的 GOPROXY 下载模块时，网络请求被阻止或无法访问。具体的错误信息显示了 `socket: permission denied`，这意味着在构建 Docker 镜像时，网络请求被阻止，可能是由于以下几个原因：

1. **网络权限问题**：在 Docker 容器中，可能没有适当的权限进行网络请求。需要确保 Docker 容器具有访问外部网络的权限。

2. **DNS 解析问题**：`lookup mirrors.aliyun.com on 100.100.2.138:53` 失败，可能是由于 DNS 解析失败或 DNS 服务器无法访问。你可以尝试使用其他 DNS 服务器，如 8.8.8.8 或 1.1.1.1。

3. **代理设置问题**：`GOPROXY` 的设置可能有问题，建议检查 URL 的格式是否正确，或者尝试使用其他的 Go 代理，例如 `https://goproxy.io`。

4. **防火墙或网络策略**：可能由于防火墙或公司网络策略阻止了 UDP/TCP 的外部请求。

以下是一些解决方案，你可以尝试以下步骤：

### 解决方案一：修改 DNS 设置
在 Dockerfile 中添加步骤来修改 DNS 服务器：
```dockerfile
RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf
```

### 解决方案二：检查和修改 GOPROXY 设置
尝试使用其他代理：
```dockerfile
RUN go env -w GOPROXY=https://goproxy.io,direct
```

### 解决方案三：检查网络权限
确保 Docker 容器有访问外部网络的权限，并检查 Docker 的网络配置。

### 解决方案四：手动下载模块
在 Dockerfile 中，手动下载所需的 Go 模块：
```dockerfile
RUN go mod tidy
```

### 示例修改后的 Dockerfile
```dockerfile
# 使用新的 GOPROXY 和修改 DNS
RUN echo "nameserver 8.8.8.8" > /etc/resolv.conf
RUN go env -w GOPROXY=https://goproxy.io,direct
RUN go mod download
```

试试这些方法，看看是否能解决问题。

---

以上来自GPT4
